default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: mom-rails
  password: A2VuLGfhzuauMfBT

development: &development
  <<: *default
  database: mom-rails_development

test: &test
  <<: *default
  database: mom-rails_test
  min_messages: WARNING

production: &production
  <<: *default
  database: mom-rails_production
